[general]
import = ["/home/jasper/.config/alacritty/themes/toml/monokai_charcoal.toml"]

# Override default background colors to make them black
[colors.primary]
# Actually this value is from the carbonfox neovim theme
background='#161616'

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "HackNerdFont"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
decorations_theme_variant = "Dark"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 83
lines = 22

# [window.padding]
# x = 20
# y = 20
