alias ...='cd ../..'
alias ..='cd ..'
alias cat='bat --color=auto --style=plain'
alias cdlx='cd $HOME/Documents/git/linux'
alias cfg='config'
alias clip='xclip -selection clip'
alias ffmpeg='ffmpeg -hide_banner'
alias ip='ip -color -br'
alias la='ls --color=auto --group-directories-first -a'
alias ll='ls --color=auto --group-directories-first -lh'
alias ls='ls --color=auto --group-directories-first'
alias neofetch='fastfetch'
alias nvimx='/usr/bin/nvim -u ~/.config/nvim/scratch.lua'
alias vim='/usr/bin/env nvim'
alias yt-dlp='yt-dlp --embed-thumbnail --cookies-from-browser firefox --external-downloader aria2c --continue'
