[[snippets]]
prefix = "fnmn"
scope = [ "rust" ]  # language id https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers
body = 'fn main () { $2/* bla bla bla */ }'
description = "log at debug level"
